// server/models/Quiz.js
const mongoose = require('mongoose');

// Define the structure for individual questions generated by the AI
const questionSchema = new mongoose.Schema({
    question: {
        type: String,
        required: true
    },
    expected_answer: {
        type: String,
        required: true
    },
    marks: {
        type: Number,
        required: true
    }
});

// Define the main Quiz structure
const quizSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
    topic: {
        type: String,
        required: true
    },
    sourceText: {
        type: String,
        required: true
    },
    teacherId: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        ref: 'User'
    },
    // --- NEW: Time limit field ---
    timeLimit: {
        type: Number,
        required: true,
        default: 15 // Time in minutes
    },
    // -----------------------------
    questions: [questionSchema]
}, {
    timestamps: true
});

const Quiz = mongoose.model('Quiz', quizSchema);
module.exports = Quiz;